# 아이리스 품종 분류
1. 라이브러리 사용
2. 데이터 준비합니다.
3. 모델을 만듭니다.
4. 모델을 학습합니다.
5. 모델을 이용합니다. 

## Resources
* https://www.youtube.com/watch?v=bu8g-Bs4Oyk&list=PLl1irxoYh2wyLwJutUZx5Q_QEEDZoXBnz&index=17
* https://github.com/blackdew/tensorflow1/blob/master/practice2-lemonade.ipynb

In [1]:
# 1. 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 2. 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# one-hot encoding
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [4]:
# print the column names
print(인코딩.columns)
print(인코딩.columns[-3:])

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
Index(['품종_setosa', '품종_versicolor', '품종_virginica'], dtype='object')


In [5]:
# 종속변수, 독립변수
독립 = 인코딩.copy().drop(인코딩.columns[-3:], axis=1)
종속 = 인코딩[인코딩.columns[-3:]]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [10]:
# 3. 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [11]:
# 4. 모델을 학습시킵니다. 
model.fit(독립, 종속, epochs=500, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0496 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0588 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0470 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0473 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0470 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0514 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0500 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0571 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0501 - accuracy: 0.9867
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.0502 - accuracy: 0.9800


In [12]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.0000000e+00 5.5204774e-10 1.1427802e-09]
 [1.0000000e+00 3.7555035e-09 6.1358763e-09]
 [1.0000000e+00 2.4878151e-09 4.6415161e-09]
 [1.0000000e+00 8.8735774e-09 1.1328045e-08]
 [1.0000000e+00 5.1039906e-10 1.0752865e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[1.1425307e-10 8.9834630e-04 9.9910164e-01]
 [5.1057386e-10 6.2053399e-03 9.9379468e-01]
 [4.0232542e-10 7.9990318e-03 9.9200094e-01]
 [1.6002198e-10 3.2821298e-04 9.9967182e-01]
 [1.6448949e-09 1.6749194e-02 9.8325080e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [13]:
# 학습한 가중치
model.get_weights()

[array([[ 0.3105186 ,  0.01899019,  0.5269902 ,  0.06505573,  0.6917634 ,
          0.14369845, -0.3146737 ,  0.07009823],
        [ 0.3994269 , -0.06778046,  0.13118352,  0.56390774, -0.06066229,
         -0.28537288, -0.13848248,  0.8605999 ],
        [-0.93937814,  0.25208333, -0.55812615,  0.5869845 ,  0.00313781,
          0.20554277,  0.6163208 , -0.3194049 ],
        [-0.56990635,  0.52754146, -0.5898556 ,  0.87492454, -0.6445474 ,
          0.29919174,  0.78190845, -0.310279  ]], dtype=float32),
 array([ 0.09840807, -0.19049804,  0.35911193, -0.12679034,  0.20749216,
        -0.04896654, -0.05010729,  0.22540691], dtype=float32),
 array([[ 0.1431853 , -0.2606877 , -0.48612556, -0.21638475,  0.9682175 ,
         -0.6123484 , -0.5742235 , -0.48107275],
        [ 0.03893661,  0.08036325,  0.08030134, -0.8686699 ,  0.07653972,
         -0.5219356 , -0.6132189 , -0.1315395 ],
        [ 0.29340097,  0.64335394, -0.70863664,  0.85108477,  0.01928946,
          0.3954984 ,  0.25836378,

In [14]:
독립.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0   5.1  3.5    1.4   0.2
1   4.9  3.0    1.4   0.2
2   4.7  3.2    1.3   0.2
3   4.6  3.1    1.5   0.2
4   5.0  3.6    1.4   0.2

In [15]:
종속.head()

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0