# 아이리스 품종 예측
1. 라이브러리 사용
2. 데이터 준비합니다.
3. 모델을 만듭니다.
4. 모델을 학습합니다.
5. 모델을 이용합니다. 

## Resources
* https://www.youtube.com/watch?v=bu8g-Bs4Oyk&list=PLl1irxoYh2wyLwJutUZx5Q_QEEDZoXBnz&index=17
* https://github.com/blackdew/tensorflow1/blob/master/practice2-lemonade.ipynb

In [1]:
# 1. 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [5]:
# 2. 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [6]:
# one-hot encoding
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [13]:
# print the column names
print(인코딩.columns)
print(인코딩.columns[-3:])

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
Index(['품종_setosa', '품종_versicolor', '품종_virginica'], dtype='object')


In [14]:
# 종속변수, 독립변수
독립 = 인코딩.copy().drop(인코딩.columns[-3:], axis=1)
종속 = 인코딩[인코딩.columns[-3:]]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [16]:
# 3. 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [21]:
# 4. 모델을 학습시킵니다. 
# model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 1ms/step - loss: 0.3237 - accuracy: 0.9533
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.9733
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.9733
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3215 - accuracy: 0.9667
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3219 - accuracy: 0.9733
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3205 - accuracy: 0.9667
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3210 - accuracy: 0.9600
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3193 - accuracy: 0.9733
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3189 - accuracy: 0.9733
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.3190 - accuracy: 0.9667
Epoch 11/100
5/5 [===========

5/5 [==============================] - 0s 2ms/step - loss: 0.2840 - accuracy: 0.9733
Epoch 85/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2837 - accuracy: 0.9733
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.2829 - accuracy: 0.9733
Epoch 87/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2838 - accuracy: 0.9667
Epoch 88/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2829 - accuracy: 0.9733
Epoch 89/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2815 - accuracy: 0.9733
Epoch 90/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2814 - accuracy: 0.9733
Epoch 91/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2821 - accuracy: 0.9733
Epoch 92/100
5/5 [==============================] - 0s 1ms/step - loss: 0.2808 - accuracy: 0.9867
Epoch 93/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2819 - accuracy: 0.9800
Epoch 94/100
5/5 [===============

In [32]:
# 모델을 이용합니다. 
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[9.88670349e-01 1.12042027e-02 1.25402148e-04]
 [9.73820090e-01 2.57595181e-02 4.20362398e-04]
 [9.83582020e-01 1.61691625e-02 2.48754513e-04]
 [9.67298925e-01 3.20491679e-02 6.51865616e-04]
 [9.89849687e-01 1.00365467e-02 1.13700225e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[3.8734483e-04 2.8473249e-01 7.1488023e-01]
 [3.8640838e-04 3.3510187e-01 6.6451174e-01]
 [5.3262792e-04 3.5033029e-01 6.4913708e-01]
 [2.8449035e-04 2.3181075e-01 7.6790470e-01]
 [6.0598477e-04 3.4893420e-01 6.5045983e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [33]:
# 학습한 가중치
model.get_weights()

[array([[-0.06698967, -0.4832852 , -1.1083641 ],
        [ 1.0622675 , -0.46651325, -0.97063273],
        [-2.0071332 ,  0.5246205 ,  1.356057  ],
        [-0.76740426, -0.11927093,  1.3101059 ]], dtype=float32),
 array([ 1.0264373 ,  0.34612355, -0.6439611 ], dtype=float32)]

In [35]:
독립.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0   5.1  3.5    1.4   0.2
1   4.9  3.0    1.4   0.2
2   4.7  3.2    1.3   0.2
3   4.6  3.1    1.5   0.2
4   5.0  3.6    1.4   0.2

In [36]:
종속.head()

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0