## tensor in tensorflow
* 1D: scalar
* 2D: vector
* 3D: matrix

In [1]:
import tensorflow as tf

In [16]:
# Initialization of Tensors
tf.constant(4)
tf.constant([1,2,3])
tf.constant([[1,2,3], [4,5,6]])
tf.ones((3,3))
tf.zeros((2,3))
tf.eye(3) # the identity matrix (eye)
tf.random.normal((3,3), mean=0, stddev=1)
tf.random.uniform((3,3), minval=0, maxval=1)
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [23]:
# type casting
x = tf.range(start=1, limit=10, delta=2)
print(x)
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [41]:
# Mathematical Operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) # or z = x + y
print(z)

z = tf.subtract(x,y) # or z = x - y
print(z)

# element-wise
z = tf.divide(x,y) # or z = x/y
print(z)
z = tf.multiply(x,y) # or z = x*y
print(z)
z = x ** 2
print(z)

# dot-product (element-wise multiplication and summation)
z = tf.tensordot(x, y, axes=1)
print(z)
z = tf.reduce_sum(x*y, axis=0)
print(z)

# matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)
z = x @ y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(
[[ 2.5028346   0.08707154 -3.3892717   2.7017684 ]
 [ 0.54962724  2.8742056  -0.1276693   0.12790847]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 2.5028346   0.08707154 -3.3892717   2.7017684 ]
 [ 0.54962724  2.8742056  -0.1276693   0.12790847]], shape=(2, 4), dtype=float32)


In [50]:
# Indexing (vector)
x = tf.range(10)
print(x)
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)
tf.Tensor([0 3], shape=(2,), dtype=int32)


In [57]:
# Indexing (matrix)
x = tf.constant([[1,2],[3,4],[5,6]])
print(x[0])
print(x[0,])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [65]:
# Reshaping
x = tf.range(9)
print(x)
x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
