# 강의 목표
* constant, variable 이 두개의 tensors의 필요성
* dataset과 같이 immutable 변하지 않는 값을 받는 노드는 constant tensors로 정의
* model parameters와 같이 mutable 변하는 값을 받는 노드는 variable tensors로 정의

https://www.inflearn.com/course/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C-%EB%94%A5%EB%9F%AC%EB%8B%9D-%EA%B5%AC%ED%98%84/lecture/57328?tab=curriculum&mm=close

In [16]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.0


In [13]:
t1 = tf.Variable([1,2,3])
t2 = tf.constant([1,2,3])

print(t1)
print(t2)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [14]:
print('=====')
print(type(t1))
print(type(t2))

=====
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


constant tensor는 EagerTensor type으로 

variable tensor는 ResourceVariable으로 나옴

In [19]:
# python list, numpy를 tensor로 변환
test_list = [1,2,3]
test_np = np.array([1,2,3])

t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print('=====')
print(t1)
print(t2)
print(type(t1))
print(type(t2))

t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)

print('=====')
print(t1)
print(t2)
print(type(t1))
print(type(t2))

=====
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
=====
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [25]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)

t3 = t1 + t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>


다른 종류의 tensor 연산 후 결과 값의 type? EagerTensor